const express = require('express')
const mongoose = require('mongoose')
const dotenv = require('dotenv')
const cors = require('cors')
dotenv.config()
const app = express()
app.use(cors())
app.use(express.json())
const authRoutes = require('./routes/auth')
const taskRoutes = require('./routes/tasks')
app.use('/api', authRoutes)
app.use('/api/tasks', taskRoutes)
app.get('/', (req, res) => res.json({ ok: true }))
const PORT = process.env.PORT || 5000
mongoose.connect(process.env.MONGO_URI).then(()=> {
  app.listen(PORT, ()=> console.log('Server running on', PORT))
}).catch(err => {
  console.error('Mongo connect error', err)
  process.exit(1)
})
